<?php

// autoload_psr4.php @generated by Composer

$vendor_copyDir = dirname(__DIR__);
$baseDir = dirname($vendor_copyDir);

return array(
    'PHPMailer\\PHPMailer\\' => array($vendor_copyDir . '/phpmailer/phpmailer/src'),
);
