<?php

// autoload_classmap.php @generated by Composer

$vendor_copyDir = dirname(__DIR__);
$baseDir = dirname($vendor_copyDir);

return array(
    'Composer\\InstalledVersions' => $vendor_copyDir . '/composer/InstalledVersions.php',
);
