<?php

// autoload_classmap.php @generated by Composer

$vendor-copyDir = dirname(__DIR__);
$baseDir = dirname($vendor-copyDir);

return array(
    'Composer\\InstalledVersions' => $vendor-copyDir . '/composer/InstalledVersions.php',
);
