<?php

// autoload_psr4.php @generated by Composer

$vendor-copyDir = dirname(__DIR__);
$baseDir = dirname($vendor-copyDir);

return array(
    'PHPMailer\\PHPMailer\\' => array($vendor-copyDir . '/phpmailer/phpmailer/src'),
);
